spring:
  cloud:
    loadbalancer:
      retry:
        enabled: false
  application:
    name: transfer-consumersdk

server:
  port: 8882

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8881/eureka/

ribbon:
  OkToRetryOnAllOperations: false
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0
  ReadTimeout: 600000
  ConnectTimeout: 6000

feign:
  client:
    registerWithEureka: true
    fetchRegistry: false
    config:
      default:
        connect-timeout: 100000
        read-timeout: 100000

